"""Deployment artifact, persistence, and smoke-verification surfaces."""

from voicey.deploy.cloud import (
    CloudArtifactGenerator,
    CloudArtifacts,
    CloudDeploymentReport,
    CloudResourceState,
    CloudResourceStore,
    CloudSmokeReport,
    LiveKitCloudDeploymentManager,
    LiveKitCloudPlan,
    PipecatCloudDeploymentManager,
    PipecatCloudPlan,
    PlatformCliRunner,
)
from voicey.deploy.cloud_smoke import LiveKitCloudSessionSmoke
from voicey.deploy.docker import (
    DockerArtifacts,
    DockerDeploymentGenerator,
    DockerSmokeResult,
    DockerSmokeVerifier,
)
from voicey.deploy.fly import (
    FlyArtifactGenerator,
    FlyArtifacts,
    FlyctlRunner,
    FlyDeploymentManager,
    FlyDeploymentReport,
    FlyPlan,
    FlyResourceState,
    FlyResourceStore,
    FlySmokeReport,
)
from voicey.deploy.persistence import (
    PersistencePreflightReport,
    RollingGenerationReport,
    docker_persistence_preflight,
    rolling_generation_invariant,
)
from voicey.deploy.railway import (
    RailwayArtifactGenerator,
    RailwayArtifacts,
    RailwayCliRunner,
    RailwayDeploymentManager,
    RailwayDeploymentReport,
    RailwayPlan,
    RailwayResourceState,
    RailwayResourceStore,
    RailwaySmokeReport,
)

__all__ = [
    "CloudArtifactGenerator",
    "CloudArtifacts",
    "CloudDeploymentReport",
    "CloudResourceState",
    "CloudResourceStore",
    "CloudSmokeReport",
    "DockerArtifacts",
    "DockerDeploymentGenerator",
    "DockerSmokeResult",
    "DockerSmokeVerifier",
    "FlyArtifactGenerator",
    "FlyArtifacts",
    "FlyDeploymentManager",
    "FlyDeploymentReport",
    "FlyPlan",
    "FlyResourceState",
    "FlyResourceStore",
    "FlySmokeReport",
    "FlyctlRunner",
    "LiveKitCloudDeploymentManager",
    "LiveKitCloudPlan",
    "LiveKitCloudSessionSmoke",
    "PersistencePreflightReport",
    "PipecatCloudDeploymentManager",
    "PipecatCloudPlan",
    "PlatformCliRunner",
    "RailwayArtifactGenerator",
    "RailwayArtifacts",
    "RailwayCliRunner",
    "RailwayDeploymentManager",
    "RailwayDeploymentReport",
    "RailwayPlan",
    "RailwayResourceState",
    "RailwayResourceStore",
    "RailwaySmokeReport",
    "RollingGenerationReport",
    "docker_persistence_preflight",
    "rolling_generation_invariant",
]
