"""Generated Markdown reference pages for stable public contracts."""

from __future__ import annotations

import inspect
import json
from pathlib import Path
from typing import Any, cast

import voicey
from voicey import results, testing, tools
from voicey.config import (
    Agent,
    Behavior,
    Limits,
    Models,
    Observability,
    Phone,
    Results,
    Voice,
    Web,
)
from voicey.errors import ERROR_CATALOG
from voicey.results.schema import WebhookEvent

API_REFERENCE_PATHS = (
    Path("docs/api/index.md"),
    Path("docs/api/config.md"),
    Path("docs/api/python.md"),
    Path("docs/api/webhooks.md"),
    Path("docs/api/errors.md"),
)

_CONFIG_MODELS = (
    Agent,
    Models,
    Voice,
    Phone,
    Web,
    Results,
    Limits,
    Observability,
    Behavior,
)
_PUBLIC_MODULES = (
    ("voicey", voicey),
    ("voicey.results", results),
    ("voicey.testing", testing),
    ("voicey.tools", tools),
)


def build_api_reference() -> dict[Path, str]:
    """Render every generated API page from importable implementation objects."""
    return {
        API_REFERENCE_PATHS[0]: _index_page(),
        API_REFERENCE_PATHS[1]: _config_page(),
        API_REFERENCE_PATHS[2]: _python_page(),
        API_REFERENCE_PATHS[3]: _webhook_page(),
        API_REFERENCE_PATHS[4]: _errors_page(),
    }


def changed_api_reference(root: Path) -> tuple[Path, ...]:
    pages = build_api_reference()
    return tuple(
        path
        for path, contents in pages.items()
        if not (root / path).is_file() or (root / path).read_text(encoding="utf-8") != contents
    )


def write_api_reference(root: Path) -> tuple[Path, ...]:
    pages = build_api_reference()
    changed = changed_api_reference(root)
    for path in changed:
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(pages[path], encoding="utf-8")
    return changed


def _index_page() -> str:
    return """<!-- Generated by scripts/update_api_reference.py; do not edit. -->
# API reference

These pages are generated from the installed public Python objects, Pydantic
serialization schemas, validated webhook model, and error catalog.

- [Configuration models](config.md)
- [Python API](python.md)
- [Webhook payload](webhooks.md)
- [Error catalog](errors.md)
- [Complete config JSON Schema](snapshots/config-schema.json)
- [Complete webhook JSON Schema](snapshots/webhook-schema.json)
- [Complete CLI surface](snapshots/cli-surface.json)

Regenerate with `uv run python scripts/update_api_reference.py`.
"""


def _config_page() -> str:
    lines = [
        "<!-- Generated by scripts/update_api_reference.py; do not edit. -->",
        "# Configuration API",
        "",
        "All models reject unknown fields and validate on assignment. Types below",
        "describe the serialized project contract.",
        "",
    ]
    for model in _CONFIG_MODELS:
        schema = model.model_json_schema(mode="serialization")
        required = set(schema.get("required", []))
        properties = schema.get("properties", {})
        lines.extend(
            [
                f"## `{model.__name__}`",
                "",
                _summary(model),
                "",
                "| Field | Serialized type | Required | Default |",
                "|---|---|---:|---|",
            ]
        )
        for name, raw_property in properties.items():
            property_schema = _mapping(raw_property)
            default = (
                "—"
                if "default" not in property_schema
                else f"`{_json_inline(property_schema['default'])}`"
            )
            lines.append(
                f"| `{name}` | `{_schema_type(property_schema)}` | "
                f"{'yes' if name in required else 'no'} | {default} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _python_page() -> str:
    lines = [
        "<!-- Generated by scripts/update_api_reference.py; do not edit. -->",
        "# Python API",
        "",
        "Only names exported through each module's `__all__` are listed.",
        "",
    ]
    for module_name, module in _PUBLIC_MODULES:
        exports = tuple(module.__all__)  # type: ignore[attr-defined]
        lines.extend([f"## `{module_name}`", ""])
        for name in exports:
            value = getattr(module, name)
            kind = (
                "class"
                if inspect.isclass(value)
                else "function"
                if callable(value)
                else "module"
                if inspect.ismodule(value)
                else "value"
            )
            signature = ""
            if callable(value) and not inspect.isclass(value):
                try:
                    signature = str(inspect.signature(value))
                except (TypeError, ValueError):
                    signature = "(signature unavailable)"
            heading = f"### `{name}{signature}`"
            if "secret" in heading.casefold():
                heading += " <!-- pragma: allowlist secret -->"
            lines.extend(
                [
                    heading,
                    "",
                    f"**Kind:** {kind}. {_summary(value)}",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def _webhook_page() -> str:
    schema = WebhookEvent.model_json_schema(by_alias=True, mode="serialization")
    definitions = _mapping(schema.get("$defs", {}))
    objects = [("WebhookEvent", schema), *sorted(definitions.items())]
    lines = [
        "<!-- Generated by scripts/update_api_reference.py; do not edit. -->",
        "# Webhook payload API",
        "",
        "The delivery worker validates this model before secret scrubbing, field",
        "redaction, canonical JSON serialization, and Standard Webhooks signing.",
        "",
    ]
    for name, raw_object in objects:
        object_schema = _mapping(raw_object)
        properties = _mapping(object_schema.get("properties", {}))
        required = set(object_schema.get("required", []))
        if not properties:
            continue
        lines.extend(
            [
                f"## `{name}`",
                "",
                "| Field | JSON type | Required |",
                "|---|---|---:|",
            ]
        )
        for field, raw_property in properties.items():
            lines.append(
                f"| `{field}` | `{_schema_type(_mapping(raw_property))}` | "
                f"{'yes' if field in required else 'no'} |"
            )
        lines.append("")
    lines.extend(
        [
            "The complete machine-readable schema is",
            "[webhook-schema.json](snapshots/webhook-schema.json).",
            "",
        ]
    )
    return "\n".join(lines)


def _errors_page() -> str:
    lines = [
        "<!-- Generated by scripts/update_api_reference.py; do not edit. -->",
        "# Error catalog API",
        "",
        "Every raised `VoiceyError` uses one of these stable codes.",
        "",
        "| Code | Cause | Fix |",
        "|---|---|---|",
    ]
    for code, definition in ERROR_CATALOG.items():
        lines.append(
            f"| [`{code}`](../errors.md#{code.casefold()}) | "
            f"{_escape(definition.cause)} | {_escape(definition.fix)} |"
        )
    lines.extend(
        [
            "",
            "See [Troubleshooting](../troubleshooting.md) for symptom-oriented routing.",
            "",
        ]
    )
    return "\n".join(lines)


def _schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", maxsplit=1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_schema_type(_mapping(item)) for item in schema["anyOf"])
    schema_type = schema.get("type", "object")
    if schema_type == "array":
        return f"array[{_schema_type(_mapping(schema.get('items', {})))}]"
    if schema_type == "object" and "additionalProperties" in schema:
        return f"object[string, {_schema_type(_mapping(schema['additionalProperties']))}]"
    return str(schema_type)


def _summary(value: object) -> str:
    doc = inspect.getdoc(value) or "No public description."
    return " ".join(doc.split("\n\n", maxsplit=1)[0].split())


def _mapping(value: object) -> dict[str, Any]:
    return cast("dict[str, Any]", value) if isinstance(value, dict) else {}


def _json_inline(value: object) -> str:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"))


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")
